### PR TITLE
Add client and overhaul UI (closes #3)

### LINKED ISSUE #3: Overhault UI
Maybe use bootstrap

### PR DESCRIPTION
**Pull request by JPSchellenberg**
I cloud not resist and added a quick, first draft of a client that overhauls the UI.
You can view the client by using
`npm install && npm run start` and openening `http://localhost:8080` in the browser. It has no functionality right now. Let me know what you think.
Screenshot 2019-03-15 at 13 47 37

### CODE REVIEW

**Comment by rtens** [comment]
I would say, let's merge this branch, plan a bit how we want to build this thing and then get started properly.

**Comment by JPSchellenberg** [comment]
> or in this case pulling 190MB of dependencies for a simple admin tool.
Keep in mind, that most of these dependencies are for the build-process only. Once the client is built, these dependencies can be omitted. If we put this into a docker-container right now, the client would only add 332 KB. My general idea is to keep everything in the same architecture and modularize as much as possible so that we could reuse modules in other tools, but let's meet and talk about it.

**Comment by rtens** [comment]
I'm not concerned about the disk space, but about the amount of dependencies/depth of the stack. Maybe I suffer from the not-invented-here-syndrome but I'm just generally wary when it comes to building something on top of a huge stack.

But I'm definitely willing to give it a try =)

**Comment by JPSchellenberg** [comment]
I definitely know what you mean. It slowed the [main project](https://github.com/Lumieducation/Lumi) down because the dependencies changed so much in the last year, but now they seem to be stable and I simply have to invest more time in maintaining rather than implementing features.

**Pull request merged**
