### PR TITLE
Server must-haves for Toolz workshop

### LINKED ISSUE #10: Implement must-haves for Toolz workshop into LumiBox server
The LumiBox Server should support the [*must-haves*](https://github.com/Lumieducation/_project/blob/toolz-workshop/publicity/2019-05-07%20Toolz/README.md#must-have)  for the [Toolz workshop](https://github.com/Lumieducation/_project/issues/26)

## Status
- [X] report system resources status
- [x] list tools

### PR DESCRIPTION
**Pull request by rtens**
[closes #10]

Implemented resource status (to test subscription infrastructure) and listing installed tools.

What do you think about it? Does the interface work for you?

### CODE REVIEW

**Comment by JPSchellenberg** [comment]
This looks good. One thing I noticed is that you named the fields differently. (You named it `state` and I named it `status`)
I defined the tool-fields in the [types.ts](https://github.com/Lumieducation/LumiBox/blob/master/client/lib/tools/types.ts). Renaming these is no problem, but I would like to have a consistent type-definition, where it easy to find. Do you have any ideas where to put it? Another question is whether to use Typescript on the server too. Do you think the project would benefit from Typescript on the backend?

**Comment by rtens** [comment]
I had actually named it `status`. But they were still called `state` in the spec draft which was obsolete anyways and is now deleted.

I'm happy with vanilla JS but also open for porting to typescript if it's worth it. But I would create a new task for that.

Anything speaking against merging this to master?

**Comment by rtens** [comment]
Queries other than images seems to be broken. Fix then merge.

**Comment by rtens** [comment]
@JPSchellenberg Could you approve this? Cause I would like to merge this branch even if we put the project on hold.

**Pull request merged**
